### ISSUE TITLE
Edit glossary files on server

### ISSUE THREAD

**Issue by ageorgou** [oracc/nisaba#10]
Will require some authentication. See also [using VS code over SSH](https://code.visualstudio.com/docs/remote/ssh).

**Comment by giordano** [comment]
Using the above mentioned extension, we can edit glossary files in an easy way without needing anything extra from us.  We may want to document the workflow, and perhaps require the extension when installing Nisaba, but apart from that there is nothing else we need to do to.

**Comment by giordano** [comment]
For the record, in order to add a dependency on the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension we need to list it under `extensionDependencies` in the [`package.json`](https://code.visualstudio.com/api/references/extension-manifest) file.

For example:
```diff
diff --git a/package.json b/package.json
index 62e33b8..1f43a28 100644
--- a/package.json
+++ b/package.json
@@ -183,5 +183,8 @@
         "vscode-textmate": "^5.2.0",
         "webpack": "^5.50.0",
         "webpack-cli": "^4.7.2"
-    }
+    },
+    "extensionDependencies": [
+	"ms-vscode-remote.remote-ssh"
+    ]
 }
```
and this will appear in the "Dependencies" tab of info page of the Nisaba extension:
![image](https://user-images.githubusercontent.com/765740/164428438-eb1026e3-5217-4159-810d-c71b7de5ab00.png)

I can make a PR with the above change if this looks good.

**Comment by ageorgou** [comment]
Looks good, should we add it now or wait until we use it more extensively (or add some instructions for setting up the connection to the server)?

**Comment by giordano** [comment]
There has been some work on glossary files in

* #105 
* #116
* #123 
* #124

I think the first big chunk of work on glossary files has been done.  There is ongoing work in #108 for #11.  However by re-reading the conversation above I think we may still want to make [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) a dependency of this package, I'll open a separate ticket for that, and close this one.
