### ISSUE TITLE
Error during communication with server

### ISSUE THREAD

**Issue by stinney** [oracc/nisaba#110]
In some cases attempting to lemmatize a text in Nisaba gives "An error has occurred: Error during communication with the server". In some cases this is a consistent (or almost consistent) event; in other cases, the lemmatization is consistently (or almost consistently) successful.

I suspect this may be connected with the large size of some of the lemmatization data files that the lemmatizer is loading and, if so, I wonder if there is a timeout on the connection that is getting triggered.

Based on my testing, it looks like I can influence the chance of success or failure by varying the list of lemmatization data sources.  When the epsd2 lemmatization is loaded the outcome is usually failure--the occasional successes may be related to file-caching or unusually low machine load.

**To Reproduce**
Here are two versions of the same test file:

a-obmc.atf:
```
&P121212=X
#project: obmc
#atf: use unicode
1. a 
#lem: a[water]N
```
a-epsd2.atf:
```
&P121212=X
#project: epsd2
#atf: use unicode
1. a 
#lem: a[water]N
```

In the obmc project, a[water]N is found in the project's glossary--the data file loaded is /home/oracc/pub/obmc/lemm-sux.sig and is 2855 lines and ~240k.  This file normally lemmatizes successfully.

In the epsd2 project, the corresponding project glossary, /home/oracc/pub/epsd2/lemm-sux.sig, is ~315k lines and 30M.  This file normally elicits the communication error (not always).

**Expected behavior**
I expect both files to lemmatize successfully every time, modulo actual network errors.

**Screenshots**
If applicable, add screenshots to help explain your problem (follow these [instructions](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files) if you need help).

**User desktop system (please complete the following information):**
 - OS: MacOS
 - Version 12.1
 - Apple chip version of VS Code

**Smartphone (please complete the following information):**

**Additional context**

I've also observed this problem helping Klaus Wagensonner via screenshare.

**Comment by ageorgou** [comment]
Thanks for the report @stinney. I can lemmatise both files successfully, but the epsd2 one does take longer. Can you check whether it is still happening for you?

There is indeed an effective timeout, in that there is a limit on how many time the server is asked for the result before giving up. If this limit is reached, the error message should indicate that. Do you remember if the full message was something like the following?
> An error has occurred: Error during communication with the server: The Oracc server was unable to elaborate response for request with id .... Please contact the Oracc server admin to look into this problem.

Alternatively, could you share the log file that Nisaba creates? This should be in your home directory, in a hidden `.nisaba` directory. This can help us see if it was a time out or some other error. Or if you have a longer ATF file that you think is likelier to demonstrate the error, that would also be useful.

If it turns out that it did time out, we can increase the limit on requests or space them out.

**Comment by stinney** [comment]
Tested new release after talking to @ageorgou  and this seems to be fixed.
